apiVersion: batch/v1
kind: Job
metadata:
  name: restgw-iac
  namespace: syfocron
spec:
  template:
    spec:
      containers:
        - name: restgw-iac
          #image: docker.pkg.github.com/{{version}}
          image: {{version}}
          command: ["restgw-iac"]
          resources:
            requests:
              memory: 64Mi
              cpu: 5m
            limits:
              memory: 64Mi
              cpu: 5m
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault
              name: vault-secrets
          env:
            - name: VAULT_PATH
              value: /var/run/secrets/nais.io/vault
      initContainers:
        - name: vks
          image: navikt/vks:29
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault
              name: vault-secrets
          env:
          - name: VKS_VAULT_ADDR
            value: https://vault.adeo.no
          - name: VKS_AUTH_PATH
            value: /kubernetes/preprod/fss
          - name: VKS_KV_PATH
            value: /kv/preprod/fss/restgw-iac/syfocron
          - name: VKS_VAULT_ROLE
            value: restgw-iac
          - name: VKS_SECRET_DEST_PATH
            value: /var/run/secrets/nais.io/vault
      serviceAccount: restgw-iac
      serviceAccountName: restgw-iac
      volumes:
        - configMap:
          defaultMode: 420
          name: ca-bundle
        - emptyDir:
          medium: Memory
          name: vault-secrets
      restartPolicy: Never
      ttlSecondsAfterFinished: 150
  backoffLimit: 4
